steps:
  - name: $_BUILDER_IMAGE
    args:
      - hugo
  - name: $_BUILDER_IMAGE
    args:
      - hugo
      - deploy
      - target=gcp
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _BUILDER_IMAGE: 'hugomods/hugo:exts'
