steps:
  - name: $_BUILDER_IMAGE
    args:
      - hugo
  - name: $_BUILDER_IMAGE
    args:
      - hugo
      - deploy
      - --target=gcp
  - name: $_BUILDER_IMAGE
    args:
      - hugo
      - deploy
      - --target=r2
    secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_SESSION_TOKEN']
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _BUILDER_IMAGE: 'hugomods/hugo:exts'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/FO_R2_AWS_ACCESS_KEY_ID/versions/1
    env: 'AWS_ACCESS_KEY_ID'
  - versionName: projects/$PROJECT_ID/secrets/FO_R2_AWS_SECRET_ACCESS_KEY/versions/1
    env: 'AWS_SECRET_ACCESS_KEY'
  - versionName: projects/$PROJECT_ID/secrets/FO_R2_AWS_SESSION_TOKEN/versions/1
    env: 'AWS_SESSION_TOKEN'